kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs-client
  uid: 06d2799f-01e8-442d-a113-c49facc9823c
  resourceVersion: '3574954'
  creationTimestamp: '2025-01-14T14:01:04Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"nfs-client"},"parameters":{"archiveOnDelete":"false"},"provisioner":"k8s-sigs.io/nfs-subdir-external-provisioner"}
    storageclass.kubernetes.io/is-default-class: 'true'
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2025-01-14T14:01:04Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:parameters':
          .: {}
          'f:archiveOnDelete': {}
        'f:provisioner': {}
        'f:reclaimPolicy': {}
        'f:volumeBindingMode': {}
    - manager: kubectl-patch
      operation: Update
      apiVersion: storage.k8s.io/v1
      time: '2025-01-16T14:12:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:allowVolumeExpansion': {}
        'f:metadata':
          'f:annotations':
            'f:storageclass.kubernetes.io/is-default-class': {}
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: 'false'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
